#---
- hosts: all
  sudo: yes
  tasks:
  - name: install node
    apt: update_cache=yes name={{ item }} state=present
    with_items:
      - nodejs
      - npm
  - name: Create Directory
    file: path=/home/ubuntu/app state=directory owner=ubuntu group=ubuntu
  - name: copy project files
    copy: src=app.js  dest=/home/ubuntu/app
  - name: copy package json
    copy: src=package.json dest=/home/ubuntu/app
  - name: "Run npm install"
    command: chdir=/home/ubuntu/app npm install
